pod:
  replicas: 1
  kind: Deployment
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
  resources:
    requests:
      memory: 128Mi
      cpu: 50m
    limits:
      memory: 256Mi
      cpu: 200m

configMap:
  theme: dark

  authentication_backend:
    file:
      enabled: true
      path: /secrets/authelia-users/users_database.yml
      password:
        algorithm: bcrypt

  session:
    name: authelia_session
    expiration: 3600
    inactivity: 300
    remember_me: 2592000
    cookies:
      - domain: cluster.afflair.app
        subdomain: auth
        default_redirection_url: https://cluster.afflair.app
    redis:
      enabled: true
      host: authelia-redis-master
      port: 6379

  storage:
    local:
      enabled: true
      path: /config/db.sqlite3

  notifier:
    filesystem:
      enabled: true
      filename: /config/notification.txt

  access_control:
    default_policy: deny
    rules:
      - domain: "auth.cluster.afflair.app"
        policy: bypass
      - domain: "*.cluster.afflair.app"
        policy: one_factor

  totp:
    disable: true

  identity_providers:
    oidc:
      enabled: true
      jwks:
        - key_id: RS256
          algorithm: RS256
          use: sig
          key:
            path: /secrets/authelia-oidc-jwks/RS256.key
      cors:
        endpoints:
          - authorization
          - token
          - revocation
          - introspection
        allowed_origins_from_client_redirect_uris: true
      clients:
        - client_id: grafana
          client_name: Grafana
          client_secret: "$pbkdf2-sha512$310000$FS9lKkJtmck/5ttUeOoelQ$cGVGPD2gI6Oa5nQR8SlkC1c.H7idj.96N6l7fmr1lmSoAUyik/rcNIPnDCG9kqErUWeileutjxz.0tDCpBgIxg"
          authorization_policy: one_factor
          token_endpoint_auth_method: client_secret_post
          redirect_uris:
            - https://grafana.cluster.afflair.app/login/generic_oauth
          scopes:
            - openid
            - profile
            - email
            - groups
          userinfo_signed_response_alg: none

secret:
  existingSecret: authelia-secrets
  additionalSecrets:
    authelia-users:
      items:
        - key: users_database.yml
          path: users_database.yml
    authelia-oidc-jwks:
      items:
        - key: RS256.key
          path: RS256.key

persistence:
  enabled: true
  storageClass: longhorn
  size: 1Gi
