---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authelia-users
  namespace: authelia
spec:
  encryptedData:
    users_database.yml: AgBWZwASwvSUP686Q+03d0aOYCFDSrYLZDwL/p/XmZWn1v8Q2FCYWYJaozqK5tdHnbl1cv0BD6oFlRRIzp9ely8hooEIYLurcacO5ARNrlsKnGKWvgw8vmEGAlMe+VtsMeuTxiOO+BBRv4y19PoSTJQRI/PlP97gfSMmu1ivUKrkQ9MGlnYNByKsLGRa0DHIIH8Pg118apiWyPaY2UL806i68DhBO9/iZNwrIAuv1PkZHRBPK6P+Gyu3D2yOOSYGgfGkTWR0nS0kPNj6yfP40lMW23R39ZEntJOdvU75C+GJPq30gew1Kw2+agNSYAnzpUF0hE+bgmeFzsttNiMXaNjNf+r97zQeGjM56MesuDIw2dKDGu7nf2wEUjD7nQEi1u7WVfKspCsqVppq1dTl5oJaIGvtq22wo5cz3wlIs7ww3Jvmhet+zHkqVr29ylhJgKEGRH1DcX1LQLMua8MKpFFRwwi1COQkqrT/6z6WVqV0GuX610OuwawiXwN8i7OLEGDpXsxfdNFH701aVAtOW2EY64tJxXiytMHzIjvMAfejHWjcyblgE+RENgctQMfnP35NTUHcGEMw8GyRGf1au8hDxMqBvBtJB7pax2TpS5cmYTIJuO1q1FTS76lzsuzpoA0DAPDjmYTG3VVpuZUyhH3q1ifasKZO9+euLaq72eQw9lkowRxYwqda+3YSrN9gGZY9MmsyznEdNXswEB7yfp6UMl09DlzSOGt/1nYywIZdny/VkmTYHNbz6ANxQLpQBwM0lN2bAtpJasZAkMsA22fsQA/wrKcTPWys3+A6cV0biYv4f1n9xQhCX1zPjtHHr8Rv7Ao3Z1MDasbotmRJVTQ6wxnrWdK4V6+wFI2EmPkpF0Azed3B8psvtsbsAG06VpZyL5HVyapHkDceK2/wljVr1Oqd5ikSYRx3HquppkJUaOtL3g==
  template:
    metadata:
      name: authelia-users
      namespace: authelia
    type: Opaque
