defaultSettings:
  defaultReplicaCount: 2
  storageMinimalAvailablePercentage: 10
  nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod

persistence:
  defaultClass: true
  defaultClassReplicaCount: 2

ingress:
  enabled: true
  ingressClassName: traefik
  host: longhorn.cluster.afflair.app
  tls: true
  tlsSecret: longhorn-tls
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: authelia-authelia@kubernetescrd
