apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-longhorn
  namespace: traefik
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 128Mi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-traefik
  namespace: traefik
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: alpine:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "Copie des données Traefik..."
              cp -av /source/. /dest/
              echo "Migration terminée."
          volumeMounts:
            - name: source
              mountPath: /source
              readOnly: true
            - name: dest
              mountPath: /dest
      volumes:
        - name: source
          persistentVolumeClaim:
            claimName: traefik
        - name: dest
          persistentVolumeClaim:
            claimName: traefik-longhorn
