apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-longhorn
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
