apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: trivy-alerts
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  groups:
    - name: trivy.vulnerabilities
      interval: 1h
      rules:
        - alert: TrivyCriticalVulnerability
          expr: |
            sum by (namespace, resource_name, container_name) (
              trivy_image_vulnerabilities{severity="CRITICAL"} > 0
            )
          for: 0m
          labels:
            severity: critical
          annotations:
            summary: "Trivy — CVE CRITICAL détectée"
            description: "{{ $labels.resource_name }} ({{ $labels.namespace }}/{{ $labels.container_name }}) a {{ $value }} CVE(s) CRITICAL."

        - alert: TrivyHighVulnerabilitySpike
          expr: |
            sum by (namespace, resource_name) (
              trivy_image_vulnerabilities{severity="HIGH"} > 10
            )
          for: 0m
          labels:
            severity: warning
          annotations:
            summary: "Trivy — Spike CVE HIGH"
            description: "{{ $labels.resource_name }} ({{ $labels.namespace }}) a {{ $value }} CVE(s) HIGH."
