configuration:
  backupStorageLocation:
    - name: aws
      provider: aws
      bucket: velero-k3s-cluster-backup
      prefix: velero
      config:
        region: eu-west-3

credentials:
  existingSecret: velero-aws-credentials

initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.10.0
    volumeMounts:
      - mountPath: /target
        name: plugins

deployNodeAgent: true
