apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki-backup
  namespace: monitoring
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: loki-backup
  namespace: monitoring
spec:
  schedule: "0 * * * *"  # toutes les heures
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: loki-backup
          restartPolicy: OnFailure
          containers:
            - name: backup
              image: amazon/aws-cli:latest
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: velero-aws-credentials-loki
                      key: access_key_id
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: velero-aws-credentials-loki
                      key: secret_access_key
                - name: AWS_DEFAULT_REGION
                  value: eu-west-3
              command:
                - /bin/sh
                - -c
                - |
                  aws s3 sync /loki-data s3://velero-k3s-cluster-backup/loki/ --delete
              volumeMounts:
                - name: loki-data
                  mountPath: /loki-data
                  readOnly: true
          volumes:
            - name: loki-data
              persistentVolumeClaim:
                claimName: storage-loki-0
