apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-backup
  namespace: velero
spec:
  schedule: "0 2 * * *"  # tous les jours à 2h du matin
  template:
    includedNamespaces:
      - monitoring
      - traefik
      - times-server
      - times-server-staging
      - argocd
      - authelia
      - crowdsec
      - beacon
      - trivyhub
      - trivyhub-landing
      - sealed-secrets
    storageLocation: aws
    ttl: 168h  # garde 7 jours de backups
    snapshotVolumes: true
    volumeSnapshotLocations:
      - csi
