apiVersion: v1
kind: ConfigMap
metadata:
  name: falco-rules-local
  namespace: falco
data:
  falco_rules.local.yaml: |
    # Whitelist ArgoCD and known sidecars contacting K8s API
    - rule: Contact K8S API Server From Container
      append: true
      exceptions:
        - name: known_k8s_api_callers
          fields: [proc.name, container.image.repository]
          values:
            - [argocd-applicat, quay.io/argoproj/argocd]
            - [python, ""]
            - [Thread-2, ""]
            - [Thread-3, ""]

    # Whitelist known trusted processes reading sensitive files
    - rule: Read sensitive file untrusted
      append: true
      exceptions:
        - name: trusted_sensitive_file_readers
          fields: [proc.exepath, container.id]
          values:
            - [/usr/lib/systemd/systemd-executor, host]
            - [/usr/bin/systemd-executor, host]
            - [/lib/systemd/systemd-executor, host]
