---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-bouncer-secret
  namespace: crowdsec
spec:
  encryptedData:
    api-key: AgCA4fz8V9ifwhTaFLCUHKdseKHLldSgDtbqVD1NlxX/+0NQtMn9Ej9dGEgEc7AFjm2ti8bvv/rwg6GAkTcdQ5wUy3j4stjOvcsfbWaRjgzCt2KpKgI3NgdVL78rkAkL+Uitlb9qyH6pyV8V6foMqFAqTJABgp3wqRDEjt1tzKrtVLkpNxSCgWdgAwV6BCE7n2tTtbg4ZH0H0EIadMlxCkJl5S8LyUxsF9tEu08m9sWasrNK7QcSu0oAwcXcngPh11FpF4TlSReKLJUkuM9Uo7+LGlQOmkk+BmJY7/jRBxOUQGFvi4zzEzD08q5hhYEHpCqzZZaXL3unqyL0vFe4+LTK7mVmXI92skTSYrzhG4/Bhga97wMwr68HFVbmCnspUjEiyRxDiZeG7y5D4OzbksLvYyITRQO5hLOK3Gpz3YSp4Lu7uMRyfzf8BChGb4YndrnmznKE0iWZi+yOJ6G/z3CNEKUysWSJQUaS38M65HdrJXteK9MzRgch/eVcIHmeXEXct2kDRyHPd0zrEtwIZXKkvaIHN10YIA0DMv3KVUrzthj5dPfQnPmcH9i+QunUDFLwgA71UOMO3V8XGd8XFOryXC556i+MooN0vgtQIZSs4b35nvKaBo5y+55bbpf/dH00wgcDsM6xN7BxNRdWXXDhjhJjrFzQYcPGKaAyujHUTbEYfsKH3O/woz91W8Gm0/YmW86SFoNVr96QGbqgoUaMYUTIXWrisKx+jqqYnM9ASr4U+/LoOT8n3sEY
  template:
    metadata:
      name: crowdsec-bouncer-secret
      namespace: crowdsec
