apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.webhook.discord: |
    url: https://discord.com/api/webhooks/1510587625399124048/ZkTCwUP3gIqzrqwtqi5yTQoQaMZJhJeLboW8G4Lg4alco05Joa2wWcPCTaR-BVWasUDN
    headers:
      - name: Content-Type
        value: application/json

  template.app-degraded: |
    webhook:
      discord:
        method: POST
        body: |
          {
            "embeds": [{
              "title": "⚠️ ArgoCD — Application dégradée",
              "description": "**{{.app.metadata.name}}** est en état `{{.app.status.health.status}}`",
              "color": 15548997,
              "fields": [
                {"name": "Sync", "value": "{{.app.status.sync.status}}", "inline": true},
                {"name": "Namespace", "value": "{{.app.spec.destination.namespace}}", "inline": true},
                {"name": "Repo", "value": "{{.app.spec.source.repoURL}}", "inline": false}
              ]
            }]
          }

  template.app-sync-failed: |
    webhook:
      discord:
        method: POST
        body: |
          {
            "embeds": [{
              "title": "❌ ArgoCD — Sync échoué",
              "description": "**{{.app.metadata.name}}** — sync failed",
              "color": 15548997,
              "fields": [
                {"name": "Message", "value": "{{.app.status.operationState.message}}", "inline": false},
                {"name": "Namespace", "value": "{{.app.spec.destination.namespace}}", "inline": true}
              ]
            }]
          }

  template.app-sync-succeeded: |
    webhook:
      discord:
        method: POST
        body: |
          {
            "embeds": [{
              "title": "✅ ArgoCD — Sync réussi",
              "description": "**{{.app.metadata.name}}** est synchronisé et healthy",
              "color": 3066993,
              "fields": [
                {"name": "Namespace", "value": "{{.app.spec.destination.namespace}}", "inline": true}
              ]
            }]
          }

  trigger.on-degraded: |
    - description: Application dégradée
      send:
        - app-degraded
      when: app.status.health.status == 'Degraded'

  trigger.on-sync-failed: |
    - description: Sync échoué
      send:
        - app-sync-failed
      when: app.status.operationState.phase in ['Error', 'Failed']

  trigger.on-sync-succeeded: |
    - description: Sync réussi
      send:
        - app-sync-succeeded
      when: app.status.operationState.phase == 'Succeeded'

  defaultTriggers: |
    - on-degraded
    - on-sync-failed
