---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
spec:
  encryptedData:
    oidc.clientSecret: AgAhnjDIvSwibsdsU/1kGcdYqqnMx3Y6QFrkxd3DSCJ0qscz5R4+L0oJx++fQPm7amTnkguMiWv/h2VyOVrMbC7LdNvGp78bR3LrepQAaj6YkhVKeZwudqPMJLzht2llyZAhki8qn4PqK+kEnlZCNcbT+UthDHdBp798AOmoA7EzflW+Kw6d1fgDP3hs3fxKNXUTROxx7qF6sqtzz9nugIdv02G8NyYqwGP9R1JzyWybTccXcMDCs9vN/pmuaWBpug5fag+UoEJNOG4FEK6HwcUCPlsi4k+zRKGOuYG4sWexHf+ktjF26ilvebZjBH4dopbfyP14WCTwGXkGfAbnaB9idjcY2lZvkSBs+iqPxIlPeJfoJs9PIPM7edT4R+aPrySmMB73Tkz+TwEeQzCSL5M2D3WGPf0wz+FKMamG2fAbQsWvaZLjSSVmPPXV1m9y8PhgenH+2caBHQiHWFmJ/rS+bzdhI4CY7G/Q437ceMjtyuPhtBWqs+ukD+hzirnQDFDfaf34C4b32zKG6VDYcXOwZJvzLOIcYtBtFXD2OcD8srtKV+hMUW3FMPqzWnlaANndaMzX1SuZs3IZmW+2o0KCZNeWSoo9OainlsZrAI7COIWhnIPsQNLUbMhHbE6i3/7YabB2pYRAta88Nw+cHiQbzqIs+bx3cWjac2+WwxmkHpKLh39Qzr52Vf2hQ4JX+ls0D96H3zh0RaeL3rQ6x8JBrOV5w3Pku1mFh5YJJoTGfw==
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-oidc-secret
      namespace: argocd
