---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sonarqube-secrets
  namespace: sonarqube
spec:
  encryptedData:
    jdbc-password: AgAJbt+ct1NW4IOJjr3XRe2e1Vjo44aVnKv82oDbVaBhQf7SZ4f8Spn6bE+9Vdder9p4dW19RvTKFqwUNA6JbSrOjdqYWE8HpZcaeg0pGBdhM5Q+RYBZJviFr/gBmmSQybiN+Z8+VEOfE5yaMEty8+hxBu8PZnb8lgaIgTEQWMrkWyi0WXgEH7qzOYTCImFX+P6IuNI9jR9XF/8HsXmJ3BTfDlMstxLhkZ4XOJ1hFAVdfnrfeWgP7v3I8nuS+uWlWDFrcZlPeQjmn+tg/cmKmyozLsSvmSuhlMKdYbpZi7206DQRpSfN6H9MNYXPg9c/3Gvr40BgphntxlsDT5/Ut8ok31LqJLWKeyregBqqfuOKrN7kEWE1XxwX4UwnSlJXzVhmGlwdAqlzJTuyQNqDLGfKMR8ydXCO8QNvGBwZxV6aQzO0SS8DBPib2kj+4dhsQE3lBOp7x9oK8m0ko44veWtUftK9G4t5hQGbS3xW2mgsqDJUU0JFvyP/BHmpEc/xF85puRy7UJveBHmKRbWsWZ/w3iCgdeHB+3AuGQZQDjxuXm+lVM70lSjixLgLe8sttx7KP9I2QiInwIZyPzUEGCUtS1eTJ191lGgDrhtxv2qmJ8mm3HD4HaP1Ck0iyhvksl/paCmc+d9xin7IYYPeIqB8EcToafurcRBSp0PieJdeq018Byp0+tHuxW3wAEygier07yURf8J+SNg=
    monitoring-passcode: AgCQLZGFzAuheEtzQGmXQIFPTywhpZbCmylojT5vD/IUDxHZGnXCmauUQgD7aFz0hwkUIabYqzfwNkT8XhoNHAHfzCR1mgBLX4klggX57djLJbPPCo2XSM78xr8xnBWmpfpVGqgqDXybkppfvIQDdXt3HneFfgpnqLOIg/k9YzIC+To1GAdCLvQ5W3WhpWACaRdSLmWZWyYGN7kPA79lu4EfKenghyjywOlF7JLQJ0G6LUaO16dLV2uqLv9Ij1kb6k/2+zrxLVsVtjb/9yzjxdo3A06jkziPi91B+3OkhedjRWJbL5F2GqcZMNh2fA4flb32nD17W/+yqRdxY9lT/nl62nobeQ2P3E47W5ArqdORYxD/EgQG2YsYOXSppS0iFlN5lheQXP0sRz2XdK0ye590JKwLz5JzKkpoSV/3kolV4J0+23EM6zcuUjmaNtkgHdIQ2pU/PH+mYPCIBhsB3hN6BMhhHg+cuKAnT8BUi/imkY/gvo79q9NzupwHXe1INxwrbU8/bsxk2972VgJw7kj0G0lTsPULY8eia9XC9I6ti5nvIK1KBy+aGjrZ2bsz28bHSZ1vSRRLVpoINsEWUSiCKvo5lHP8GBBilaFRMVpmC88+FwxYP0T+yF2v2v3T5eR2zAj8pp7dAMvk9te/dl8+SwnsspEpjXHWlLi81AZkiWEEvDDIgvot1C5RLtHyN3mNpS4xLIRrOtGAZueU8g24Kv0Shg==
  template:
    metadata:
      name: sonarqube-secrets
      namespace: sonarqube
    type: Opaque
