controller:
  replicaCount: 1

  serviceType: ClusterIP

  ingress:
    enabled: false

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi

  jenkinsUrl: "https://jenkins.cluster.afflair.app"

persistence:
  enabled: true
  storageClass: local-path
  size: 10Gi

agent:
  enabled: true
