---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jenkins-oidc-secret
  namespace: jenkins
spec:
  encryptedData:
    clientSecret: AgDI7ONjRhuc19K4zIJoP0biySGgiwJVuLYVNcU2k3uOCUU8JUqKSek3UEG/TgwcKwXyWfHaSEbLMh7h0qTdACh3dyS0TmDu7Ds60EGT6bJ83GPlYgumY0h691NU2Ypb/ZBVFegwveOsOk3tpWTuQ0+SNclcu6FPS7MaSKSFSh3ln4J3ZbcpYeya6fgJTIXNfP+dFKxHw/PQk/oP9IhzTxpMJN2SvpIGMi88BOxne65b1TfgW2IfGugn4/qFsp2BlxVbDjSJ2Waz5L/e0Ni+AQ2EthAccmpVQosXwQzBhwpCi6nxDRbtsf/cKXIBKpiGnm28Rkp9h3tnny0qfNXvBU5arTGfMP/FHjDSDwAXH7xqm8lE0fklhJMjNlNSnkOcWDF2E5am6YACmPCh/DsqlCDFcJRdWZpMRDGhwVP1BcIEjadtW4FRsJSuFKgzhpkQmwiAI6eZMEN0AEEVAYQ9ktJLh3oIINvvcA+GT2Cd8PknHdfkchXTJ8SfNazzNAwPWNqgGypRUQbmLoXurbvv3VL8AQsGDUe4ZSNJS4jpIPclwkY7hPPI/AHGUZ5PERI06oclU8vjwmixxcm1EPObKIMnUDT0DGJXTyxqOjl0h4BSOE1B4eNkdJLkCLkEjpPlkXuDP1I06itfGoTb8aICqcs7DdB2Odf9Koll5VF9LdMOaxWOUU5jooUsVFJvTIN/yR3mpuRWOaxlLF+grCQqhwzyyMqS0DjzpYT68Jay62LpCw==
  template:
    metadata:
      name: jenkins-oidc-secret
      namespace: jenkins
