apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authelia-redis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: "25.5.3"
    helm:
      releaseName: authelia-redis
      valuesObject:
        architecture: standalone
        auth:
          enabled: false
        master:
          persistence:
            enabled: true
            storageClass: local-path
            size: 1Gi
          resources:
            requests:
              memory: 64Mi
              cpu: 20m
            limits:
              memory: 128Mi
              cpu: 100m
  destination:
    server: https://kubernetes.default.svc
    namespace: authelia
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
