apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: beacon
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/theo-mrn/beacon
    targetRevision: main
    path: charts/beacon
    helm:
      values: |
        ingress:
          enabled: true
          host: beacon.cluster.afflair.app
          tls: true
        wazuh:
          indexerURL: "https://indexer.wazuh.svc.cluster.local:9200"
          user: "admin"
          password: "SecretPassword"
  destination:
    server: https://kubernetes.default.svc
    namespace: beacon
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
