apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://falcosecurity.github.io/charts
    chart: falco
    targetRevision: "4.*"
    helm:
      valuesObject:
        driver:
          kind: modern_ebpf
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 512Mi
        falco:
          json_output: true
          json_include_output_property: true
          rules_files:
            - /etc/falco/falco_rules.yaml
            - /etc/falco/falco_rules.local.yaml
            - /etc/falco/rules.d
          syscall_event_drops:
            actions:
              - log
            rate: 0.03333
            max_burst: 10
          syscall_buf_size_preset: 4
        falcosidekick:
          enabled: true
          config:
            loki:
              hostport: "http://loki.monitoring.svc.cluster.local:3100"
              minimumpriority: "notice"
              customlabels: "app:falco,cluster:afflair"
            discord:
              webhookurl: "https://discord.com/api/webhooks/1510199630246187162/Xe5yBndY-yYXH08whnW5VERnbjgGYTvxmPr7E3S-897vIqKVWAimJgIqWDIJZicgupid"
              minimumpriority: "warning"
          webui:
            enabled: false
        tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/control-plane
            operator: Exists

        customRules:
          falco_rules.local.yaml: |-
            - rule: Contact K8S API Server From Container
              override:
                exceptions: append
              exceptions:
                - name: known_k8s_api_callers
                  fields: [proc.exepath]
                  values:
                    - [/usr/local/bin/argocd]
                    - [/usr/local/bin/python3.14]
                    - [/usr/local/bin/python3.15]

            - rule: Read sensitive file untrusted
              override:
                exceptions: append
              exceptions:
                - name: trusted_sensitive_file_readers
                  fields: [proc.exepath, container.id]
                  values:
                    - [/usr/lib/systemd/systemd-executor, host]
                    - [/usr/bin/systemd-executor, host]
                    - [/lib/systemd/systemd-executor, host]

            - rule: Clear Log Activities
              override:
                exceptions: append
              exceptions:
                - name: lynis_log_write
                  fields: [proc.name, fd.name]
                  values:
                    - [lynis, /var/log/lynis.log]
                    - [lynis, /var/log/lynis-report.dat]
                    - [dash, /var/log/lynis.log]
                    - [dash, /var/log/lynis-report.dat]
  destination:
    server: https://kubernetes.default.svc
    namespace: falco
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
