apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jenkins.io
    chart: jenkins
    targetRevision: "5.9.54"
    helm:
      valuesObject:
        controller:
          replicaCount: 1
          serviceType: ClusterIP
          ingress:
            enabled: false
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 2Gi
          jenkinsUrl: "https://jenkins.cluster.afflair.app"
          probes:
            startupProbe:
              failureThreshold: 60
              periodSeconds: 10
              timeoutSeconds: 5

        sidecars:
          configAutoReload:
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                cpu: 100m
                memory: 128Mi
          additionalPlugins:
            - oic-auth:4.718.ve731df6ca_88a_
          additionalExistingSecrets:
            - name: jenkins-oidc-secret
              keyName: clientSecret
          JCasC:
            securityRealm: |-
              oic:
                clientId: "jenkins"
                clientSecret: "${jenkins-oidc-secret-clientSecret}"
                serverConfiguration:
                  manual:
                    issuer: "https://auth.cluster.afflair.app"
                    authorizationServerUrl: "https://auth.cluster.afflair.app/api/oidc/authorization"
                    tokenServerUrl: "https://auth.cluster.afflair.app/api/oidc/token"
                    tokenAuthMethod: "client_secret_post"
                    userInfoServerUrl: "https://auth.cluster.afflair.app/api/oidc/userinfo"
                    jwksServerUrl: "https://auth.cluster.afflair.app/jwks.json"
                    endSessionUrl: "https://auth.cluster.afflair.app/api/oidc/end-session"
                    scopes: "openid profile email groups"
                userNameField: "preferred_username"
                fullNameFieldName: "name"
                emailFieldName: "email"
                groupsFieldName: "groups"
                logoutFromOpenidProvider: true
                postLogoutRedirectUrl: "https://jenkins.cluster.afflair.app"

            authorizationStrategy: |-
              loggedInUsersCanDoAnything:
                allowAnonymousRead: false

        persistence:
          enabled: true
          storageClass: local-path
          size: 10Gi

        agent:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
