apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube-db
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: "18.*"
    helm:
      releaseName: sonarqube-db
      valuesObject:
        auth:
          database: sonarqube
          username: sonarqube
          password: sonarqube
        primary:
          persistence:
            size: 5Gi
            storageClass: local-path
  destination:
    server: https://kubernetes.default.svc
    namespace: sonarqube
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
