apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: times-server-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/theo-mrn/time_server
    targetRevision: gitops/prod
    path: kubernetes/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: times-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: times-server-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/theo-mrn/time_server
    targetRevision: gitops/staging
    path: kubernetes/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: times-server-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
